server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
spring:
  security:
    user:
      name: pluralsight
      password: pluralsight
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/Saqsy/pluralsight-spring-cloud-config.git
          search-paths:
            - station*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/Saqsy/pluralsight-spring-cloud-config-perf.git
              search-paths:
                - 'station*'